### ISSUE TITLE
deferred problem with function signatures

### ISSUE THREAD

**Issue by kirk86** [emacsorphanage/company-jedi#34] opened 2019-10-10 15:25 UTC
I am still getting the following problem regarding function signatures
![image](https://user-images.githubusercontent.com/2902390/66582784-389f1d00-eb7a-11e9-80fa-2873536c64bc.png)

According to https://github.com/syohex/emacs-company-jedi/issues/24 and https://github.com/tkf/emacs-jedi/pull/294 and https://github.com/tkf/emacs-jedi/pull/296 the problem seems to be flagged as resolved but I still get the same issue, any ideas what's causing it?

**Comment by gonewest818** [comment] 2020-03-24 00:51
marking duplicate of #24, please continue the discussion in that ticket.

**Closed by gonewest818** 2020-03-24 00:51 UTC
Labels: duplicate
